name: .NET Core

on:
  push:
    branches: [ development, release ]
  pull_request:
    branches: [ development, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore TP-VoiceMeeter
    - name: Build
      run: dotnet build --configuration Release --no-restore TP-VoiceMeeter/TP-VoiceMeeter.csproj
    - name: Publish
      run: dotnet publish --configuration Release --no-restore TP-VoiceMeeter/TP-VoiceMeeter.csproj -o package/TP-VoiceMeeter/
    - name: Package
      run: cd package && zip -v -r TP-VoiceMeeter.tpp TP-VoiceMeeter
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TP-VoiceMeeter.tpp
        package/path: TP-VoiceMeeter.tpp